<?php
declare(strict_types=1);
require dirname(__DIR__) . '/src/bootstrap.php';
require dirname(__DIR__) . '/src/Crypto.php';
require dirname(__DIR__) . '/src/PopClient.php';
require dirname(__DIR__) . '/src/MimeParser.php';
require dirname(__DIR__) . '/src/MailService.php';
$route = rtrim(parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH) ?: '/', '/') ?: '/';
$method = $_SERVER['REQUEST_METHOD'];

if ($route === '/login') {
    if ($method === 'POST') { verify_csrf(); if (hash_equals($config['admin_user'], (string)$_POST['username']) && password_verify((string)$_POST['password'], $config['admin_password_hash'])) { session_regenerate_id(true); $_SESSION['authenticated']=true; redirect('/'); } $error='아이디 또는 비밀번호가 올바르지 않습니다.'; }
    ?><!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/assets/style.css"><title>로그인</title></head><body class="login"><form method="post" class="login-card"><div class="logo">CC</div><h1><?=h($config['app_name'])?></h1><p>관리자 계정으로 로그인하세요.</p><?php if(isset($error)):?><div class="alert error"><?=h($error)?></div><?php endif?><input type="hidden" name="_token" value="<?=csrf_token()?>"><label>관리자 아이디<input name="username" autocomplete="username" required></label><label>비밀번호<input type="password" name="password" autocomplete="current-password" required></label><button class="button primary">로그인</button></form></body></html><?php exit;
}
require_login();
if ($route === '/logout' && $method === 'POST') { verify_csrf(); session_destroy(); redirect('/login'); }
if ($route === '/health') { header('Content-Type: application/json'); echo json_encode(['status'=>'ok']); exit; }

if ($route === '/settings' && $method === 'POST') {
    verify_csrf();
    $host=trim((string)$_POST['host']); $port=filter_var($_POST['port'],FILTER_VALIDATE_INT,['options'=>['min_range'=>1,'max_range'=>65535]]);
    if ((!filter_var($host,FILTER_VALIDATE_DOMAIN,FILTER_FLAG_HOSTNAME) && !filter_var($host,FILTER_VALIDATE_IP)) || !$port) { $_SESSION['flash']=['type'=>'error','message'=>'서버 주소 또는 포트를 확인하세요.']; redirect('/settings'); }
    $stmt=$pdo->prepare('INSERT INTO pop_accounts(name,host,port,username,password_cipher,use_tls,enabled,delete_after_receive) VALUES(?,?,?,?,?,?,?,?)');
    $stmt->execute([trim((string)$_POST['name']),$host,$port,trim((string)$_POST['username']),(new Crypto($config['app_key']))->encrypt((string)$_POST['password']),isset($_POST['use_tls']),isset($_POST['enabled']),isset($_POST['delete_after_receive'])]);
    $_SESSION['flash']=['message'=>'POP 계정을 저장했습니다.']; redirect('/settings');
}
if (preg_match('#^/settings/(\d+)/(fetch|delete)$#',$route,$m) && $method==='POST') {
    verify_csrf(); $stmt=$pdo->prepare('SELECT * FROM pop_accounts WHERE id=?');$stmt->execute([(int)$m[1]]);$account=$stmt->fetch(); if(!$account){http_response_code(404);exit('계정을 찾을 수 없습니다.');}
    if($m[2]==='delete'){ $has=$pdo->prepare('SELECT COUNT(*) FROM email_messages WHERE account_id=?');$has->execute([$account['id']]); if((int)$has->fetchColumn()>0){$pdo->prepare('UPDATE pop_accounts SET enabled=0 WHERE id=?')->execute([$account['id']]);$message='수신 메일이 있어 계정을 비활성화했습니다.';}else{$pdo->prepare('DELETE FROM pop_accounts WHERE id=?')->execute([$account['id']]);$message='계정을 삭제했습니다.';} $_SESSION['flash']=['message'=>$message];redirect('/settings'); }
    try{$count=(new MailService($pdo,$config))->fetch($account);$_SESSION['flash']=['message'=>"새 메일 {$count}건을 저장했습니다."];}catch(Throwable $e){$_SESSION['flash']=['type'=>'error','message'=>'POP 수신 실패: '.$e->getMessage()];}redirect('/settings');
}
if (preg_match('#^/attachment/(\d+)$#',$route,$m)) { $stmt=$pdo->prepare('SELECT * FROM attachments WHERE id=?');$stmt->execute([(int)$m[1]]);$a=$stmt->fetch();if(!$a||!is_file($a['storage_path'])){http_response_code(404);exit;}header('Content-Type: '.$a['mime_type']);header('X-Content-Type-Options: nosniff');header("Content-Disposition: attachment; filename*=UTF-8''".rawurlencode($a['filename']));readfile($a['storage_path']);exit; }

ob_start();
if ($route === '/') { $title='수집 현황';$accounts=(int)$pdo->query('SELECT COUNT(*) FROM pop_accounts')->fetchColumn();$messages=(int)$pdo->query('SELECT COUNT(*) FROM email_messages')->fetchColumn();$errors=(int)$pdo->query('SELECT COUNT(*) FROM pop_accounts WHERE last_error IS NOT NULL')->fetchColumn();$latest=$pdo->query('SELECT * FROM email_messages ORDER BY received_at DESC LIMIT 5')->fetchAll(); ?>
<section class="cards"><article><span>POP 계정</span><strong><?=$accounts?></strong><small>등록된 수신 계정</small></article><article><span>수신 메일</span><strong><?=$messages?></strong><small>MariaDB 메타데이터 / 파일 원문</small></article><article><span>연결 오류</span><strong><?=$errors?></strong><small>확인이 필요한 계정</small></article></section><section class="panel"><div class="panel-title"><div><h2>최근 받은 메일</h2><p>가장 최근 저장된 5건입니다.</p></div><a class="button ghost" href="/mail">전체 보기</a></div><?php if($latest):?><table><thead><tr><th>제목</th><th>보낸 사람</th><th>수신 시각</th></tr></thead><tbody><?php foreach($latest as $mail):?><tr><td><a href="/mail/<?=$mail['id']?>"><?=h($mail['subject']?:'(제목 없음)')?></a></td><td><?=h($mail['sender'])?></td><td><?=h($mail['received_at'])?></td></tr><?php endforeach?></tbody></table><?php else:?><div class="empty"><b>아직 받은 메일이 없습니다.</b><span>POP 계정을 등록한 뒤 지금 받기를 실행하세요.</span></div><?php endif?></section>
<?php } elseif ($route === '/settings') { $title='POP 계정 설정';$accounts=$pdo->query('SELECT * FROM pop_accounts ORDER BY id')->fetchAll(); ?>
<div class="columns"><section class="panel"><div class="panel-title"><div><h2>등록 계정</h2><p>비밀번호는 암호화되어 저장됩니다.</p></div></div><?php foreach($accounts as $a):?><article class="account"><div><b><?=h($a['name'])?></b><span><?=h($a['username'])?> · <?=h($a['host'])?>:<?=$a['port']?></span><?php if($a['last_error']):?><em><?=h($a['last_error'])?></em><?php endif?></div><div class="actions"><span class="pill <?=$a['enabled']?'':'muted'?>"><?=$a['enabled']?'활성':'중지'?></span><form method="post" action="/settings/<?=$a['id']?>/fetch"><input type="hidden" name="_token" value="<?=csrf_token()?>"><button class="button ghost">지금 받기</button></form><form method="post" action="/settings/<?=$a['id']?>/delete"><input type="hidden" name="_token" value="<?=csrf_token()?>"><button class="icon-button" aria-label="삭제">×</button></form></div></article><?php endforeach?><?php if(!$accounts):?><div class="empty"><b>등록된 계정이 없습니다.</b></div><?php endif?></section><section class="panel form-panel"><h2>새 POP 계정</h2><form method="post"><input type="hidden" name="_token" value="<?=csrf_token()?>"><label>표시 이름<input name="name" placeholder="카운터 수신함" required maxlength="100"></label><label>POP 서버<input name="host" placeholder="pop.example.invalid" required maxlength="255"></label><div class="form-row"><label>포트<input type="number" name="port" value="995" min="1" max="65535" required></label><label class="check"><input type="checkbox" name="use_tls" checked>TLS 사용</label></div><label>사용자 이름<input name="username" autocomplete="username" required maxlength="255"></label><label>비밀번호<input type="password" name="password" autocomplete="new-password" required></label><label class="check"><input type="checkbox" name="enabled" checked>자동 수신 활성화</label><label class="check"><input type="checkbox" name="delete_after_receive">수신 후 서버에서 삭제</label><button class="button primary">계정 저장</button></form></section></div>
<?php } elseif ($route === '/mail') { $title='받은 메일';$page=max(1,(int)($_GET['page']??1));$total=(int)$pdo->query('SELECT COUNT(*) FROM email_messages')->fetchColumn();$stmt=$pdo->prepare('SELECT e.*,p.name account_name FROM email_messages e JOIN pop_accounts p ON p.id=e.account_id ORDER BY e.received_at DESC LIMIT 20 OFFSET ?');$stmt->bindValue(1,($page-1)*20,PDO::PARAM_INT);$stmt->execute();$mails=$stmt->fetchAll();?><section class="panel"><div class="panel-title"><div><h2>메일 보관함</h2><p>POP으로 수신한 메일입니다.</p></div></div><?php if($mails):?><table><thead><tr><th>제목</th><th>보낸 사람</th><th>계정</th><th>첨부</th><th>수신 시각</th></tr></thead><tbody><?php foreach($mails as $mail):?><tr><td><a href="/mail/<?=$mail['id']?>"><?=h($mail['subject']?:'(제목 없음)')?></a></td><td><?=h($mail['sender'])?></td><td><?=h($mail['account_name'])?></td><td><?=$mail['attachment_count']?></td><td><?=h($mail['received_at'])?></td></tr><?php endforeach?></tbody></table><?php else:?><div class="empty"><b>저장된 메일이 없습니다.</b></div><?php endif?></section>
<?php } elseif (preg_match('#^/mail/(\d+)$#',$route,$m)) { $stmt=$pdo->prepare('SELECT e.*,p.name account_name FROM email_messages e JOIN pop_accounts p ON p.id=e.account_id WHERE e.id=?');$stmt->execute([(int)$m[1]]);$mail=$stmt->fetch();if(!$mail){http_response_code(404);exit('메일을 찾을 수 없습니다.');}$stmt=$pdo->prepare('SELECT * FROM attachments WHERE email_id=?');$stmt->execute([$mail['id']]);$attachments=$stmt->fetchAll();$title='메일 상세';?><section class="panel mail"><a class="back" href="/mail">← 받은 메일</a><h2><?=h($mail['subject']?:'(제목 없음)')?></h2><dl><dt>보낸 사람</dt><dd><?=h($mail['sender'])?></dd><dt>받는 사람</dt><dd><?=h($mail['recipients'])?></dd><dt>수신 계정</dt><dd><?=h($mail['account_name'])?></dd><dt>수신 시각</dt><dd><?=h($mail['received_at'])?></dd></dl><div class="body"><?=h($mail['text_body']?:'텍스트 본문이 없습니다.')?></div><?php if($attachments):?><h3>첨부 파일</h3><div class="attachments"><?php foreach($attachments as $a):?><a href="/attachment/<?=$a['id']?>"><b><?=h($a['filename'])?></b><span><?=h($a['mime_type'])?> · <?=round($a['size_bytes']/1024,1)?> KB</span></a><?php endforeach?></div><?php endif?></section>
<?php } else { http_response_code(404);$title='페이지를 찾을 수 없습니다';?><section class="panel empty">요청한 페이지가 없습니다.</section><?php }
$content=ob_get_clean();require dirname(__DIR__).'/templates/layout.php';
